### ISSUE TITLE
Fresh clone is missing referenced projects

### ISSUE THREAD

**Issue by mattbenic** [roubachof/Xamarin-Forms-Practices#1]
Cloning with recursion and checking out master of the repo, and then building (OSX, VS for Mac, attempting to build SillyCompany.Mobile.Practices.iOS) results in numerous errors and warnings. The following primary warnings/errors likely lead to the rest:

/Users/mattbenic/Documents/work/misc/Xamarin-Forms-Practices/SillyCompany.Mobile.Practices/Presentation/Views/AlternateSillySquareCell.xaml: Error: The target "UpdateDesignTimeXaml" does not exist in the project. (SillyCompany.Mobile.Practices)

/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning: The referenced project '../Sharpnado.Presentation.Forms/Sharpnado.Infrastructure/Sharpnado.Infrastructure.csproj' does not exist. (SillyCompany.Mobile.Practices)

/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning: The referenced project '../Sharpnado.Presentation.Forms/Sharpnado.Presentation.Forms/Sharpnado.Presentation.Forms.csproj' does not exist. (SillyCompany.Mobile.Practices)

/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets(9,9): Warning MSB3884: Could not find rule set file "../Sharpnado.Presentation.Forms/Sharpnado.Infrastructure/StyleCopRules.ruleset". (MSB3884) (SillyCompany.Mobile.Practices)

**Comment by roubachof** [comment]
Sorry mate but can't repro.

Just did:

1. git clone --recurse-submodules https://github.com/roubachof/Xamarin-Forms-Practices.git
2. click debug on iPhone XR iOS 12.1 on VS 2017 on PC
3. click debug on Nexus 5 simulator

works flawlessly at first try...

**Comment by mattbenic** [comment]
Apologies, I re-did the clone and it now seems fine. Something must have failed on my first attempt that I didn't notice :)
