### ISSUE TITLE
Unable to fetch: git submodule update --init

### ISSUE THREAD

**Issue by sattasundar** [roubachof/Xamarin-Forms-Practices#10]
D:\GitSharpnado\Xamarin-Forms-Practices>git submodule update --init
Submodule 'Sharpnado.HorizontalListView' (git@github.com:roubachof/Sharpnado.HorizontalListView.git) registered for path 'Sharpnado.HorizontalListView'
Submodule 'Sharpnado.MaterialFrame' (git@github.com:roubachof/Sharpnado.MaterialFrame.git) registered for path 'Sharpnado.MaterialFrame'
Submodule 'Sharpnado.Tabs' (git@github.com:roubachof/Sharpnado.Tabs.git) registered for path 'Sharpnado.Tabs'
Cloning into 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.HorizontalListView'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:roubachof/Sharpnado.HorizontalListView.git' into submodule path 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.HorizontalListView' failed
Failed to clone 'Sharpnado.HorizontalListView'. Retry scheduled
Cloning into 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.MaterialFrame'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:roubachof/Sharpnado.MaterialFrame.git' into submodule path 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.MaterialFrame' failed
Failed to clone 'Sharpnado.MaterialFrame'. Retry scheduled
Cloning into 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.Tabs'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:roubachof/Sharpnado.Tabs.git' into submodule path 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.Tabs' failed
Failed to clone 'Sharpnado.Tabs'. Retry scheduled
Cloning into 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.HorizontalListView'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:roubachof/Sharpnado.HorizontalListView.git' into submodule path 'D:/GitSharpnado/Xamarin-Forms-Practices/Sharpnado.HorizontalListView' failed
Failed to clone 'Sharpnado.HorizontalListView' a second time, aborting

**Comment by sattasundar** [comment]
@roubachof can you please help on this.

**Comment by HeiDimples** [comment]
Does anyone solve the same problem？

**Comment by roubachof** [comment]
.gitmodules fixed
