### ISSUE TITLE
Is it possible to better customize the look and feel of the TabHost and the Tabs?

### ISSUE THREAD

**Issue by cesar-moya** [roubachof/Xamarin-Forms-Practices#3]
Currently it appears you can only change the basic properties (background color, label color, selected and unselected). is it possible to add the ability to customize things more? for instance what if i'd want tabs that have rounded edges on the first and last tab? or for instance configure a different color for the borders of the tabs?

Thanks for making a great component!

**Comment by roubachof** [comment]
You can do whatever you what just override TabItem and get wild. For an example of custom tabs see this: https://www.sharpnado.com/pure-xamarin-forms-tabs/ and the SpamTab in the sample.
