### ISSUE TITLE
on select tab it execute many time

### ISSUE THREAD

**Issue by luki06** [roubachof/Xamarin-Forms-Practices#4]
Hi ,
So as the title say when i select a tab it execute more than one time here is my code `
 if (e.SelectedPosition.ToString() == "2")
            {
                FillUpdateUser();
                lbl_title.Text = "Actualizar usario";
                viewUsers.IsVisible = false;
                AddUsers.IsVisible = false;
                UpdateUsers.IsVisible = true;
                RemoveUsers.IsVisible = false;
            }`
FillUpdateUser() is a methode to fill a picker it fillet many time is it a bug or something i did wrong thanks.

**Comment by roubachof** [comment]
Sorry don't understand the issue, also this is not the repo for the component this is the repo of the sample app...
