### ISSUE TITLE
Cannot run this sample app???

### ISSUE THREAD

**Issue by john-dalsgaard** [roubachof/Xamarin-Forms-Practices#5]
I downloaded this app as a zip, unpacked it and launched it in Visual Studio 2019 (for Mac). And there are all sorts of missing files...

<img width="294" alt="image" src="https://user-images.githubusercontent.com/2842073/67468610-182b9400-f64b-11e9-8016-a159c61b9950.png">

I have tried to remove the "Sharpnado" folder and add the NuGet packages to the Silly app instead - but it won't run (more than 860 warnings etc.) - so that is definitely not the way ahead.

Also tried to download the Sharpnado.presentation.forms project and copy the files manually into this project. But couldn't make it work - so I must be doing it all wrong.

Would appreciate if you could help me install the app to see the functions live :-)

**Comment by roubachof** [comment]
Hi John! I'm afraid this sample won't work with download as zip feature cause it has sub modules. You need to get it with a gut client with fork or gitkraken....

**Comment by john-dalsgaard** [comment]
Ok, thanks....

I'm really just trying to see how little I need to implement to obtain this layout:

![image](https://user-images.githubusercontent.com/2842073/67476361-32b83a00-f658-11e9-970b-b9ea3031b16f.png)

The bottom tabs I already have working - so not sure I'll change that (at first, anyway) - but need a simple way to obtain the views with top tabs (with the underlining) as per the image :-)

But it is a little difficult just looking at your code to find out what I need. I'm also using Prism for MVVM and navigation - and not sure how much that would interfere with your code.

But I really think that your code looks great - I should just have found it earlier...

**Comment by john-dalsgaard** [comment]
... I can see that you use a Grid for laying out the tabbar and the content area - but where do the tab titles come from???

**Comment by john-dalsgaard** [comment]
I tried to clone it using SourceTree.... It didn't bring down the the missing bits and pieces.

So now I have forked it - and clone it using the URL in SourceTree:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2842073/67477960-6ea0ce80-f65b-11e9-8a74-22f2d2304be9.png">

I also tried to tick "Recurse submodules".... But still see the same missing parts as in the first screen shot. What was it that I did not understand from your suggestion???

**Comment by john-dalsgaard** [comment]
Found a solution. Cannot make the cloned project work - but had [another sample](https://github.com/Depechie/CollectionViewChallenge) that I could make work - and then start playing with (although it stopped working when I updated this package from  v.1.1.0 to v.1.3.0 - but that is another story)

**Comment by john-dalsgaard** [comment]
Hmmm... obviously, there was a breaking change in v.1.3.0 :-)

But... moving the tab items inside the `TabHostView.Tabs` does not solve it. The content from the pages does not show...

This is my very simple attempt:
```
        <StackLayout>
           <Grid RowSpacing="0" ColumnSpacing="0" Margin="0,40,0,0">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                
                <tabs:TabHostView BackgroundColor="White"
                                  ShadowType="Bottom"
                                  SelectedIndex="{Binding Source={x:Reference Switcher}, Path=SelectedIndex, Mode=TwoWay}"
                                  Grid.Row="0">
                    <tabs:TabHostView.Tabs>
                        <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="Tab 1" />
                        <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="Tab 2" />
                        <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="Tab 3" />
                    </tabs:TabHostView.Tabs>
                </tabs:TabHostView>

                <ScrollView Grid.Row="1">
                    <tabs:ViewSwitcher Animate="True" SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">
                        <views:Tab1View />
                        <customViews:LazyView x:TypeArguments="views:Tab2View" />
                        <customViews:LazyView x:TypeArguments="views:Tab3View" />
                    </tabs:ViewSwitcher>
                </ScrollView>
            </Grid>
        </StackLayout>
```
Can anyone nail the problem?
